#!/usr/bin/env bash

set -e

if [[ $(ls $1) ]]; then
    INPUT=$(cat $1)
else
    INPUT=$(</dev/stdin)
fi

if [ "x$CI_API_V4_URL" != "x" ] ; then
    # if we're running as a CI job, pick the provided API base url unless
    # overridden
    GITLAB_API_URL="${GITLAB_API_URL:-$CI_API_V4_URL}"
else
    # otherwise, use gitlab.com's API URL unless overridden
    GITLAB_API_URL="${GITLAB_API_URL:-https://gitlab.com/api/v4}"
fi

CONTENT=$(jq --null-input --arg yaml "$(<${INPUT})" '.content=$yaml')
RESPONSE=$(curl -X POST "${GITLAB_API_URL}/ci/lint" -H 'Content-Type: application/json' -H "private-token: ${private_token}" --data @-)
STATUS=$(echo $RESPONSE | jq -r '.status')

if [[ $STATUS == 'valid' ]]; then
    echo "configuration is valid"
    exit 0
elif [[ $STATUS == 'invalid' ]]; then
    echo "configuration is invalid"
    echo $RESPONSE | jq '.errors'
    exit -1
else
    echo "configuration is invalid, unknown status '$STATUS'"
    exit -2
fi

